sudo: required

language: python

os:
  - linux
  #- osx

python:
  - "2.7"
  #- "3.6"

services:
  - docker

install:
  - ls
  - git clone https://github.com/JohannesBuchner/BXA
  - cd BXA
  - docker pull johannesbuchner/bxa_absorbed:latest

script:
  - cd testsrc
  - rm *.nh
  - python ../fixkeywords.py combined_src.pi combined_bkg.pi combined_src.rmf combined_src.arf
  - git checkout .
  - python ../gal.py pn_src.fits
  #- docker run $XDOCKERARGS -v $PWD:/opt/example/ -e FILENAME=combined_src.pi -e ELO=0.5 -e EHI=8 -ti johannesbuchner/bxa_absorbed 


