name: Test conda-based Sherpa
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    defaults:
      run:
        # this is needed, because otherwise conda env is not available
        shell: bash -l {0}
        
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          channels: conda-forge, sherpa
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true
          mamba-version: "*"
 
      - name: Set directory names
        run: |
          echo "MODELDIR=$HOME/Downloads/models" >> $GITHUB_ENV

      - name: Cache models
        uses: pat-s/always-upload-cache@v2.1.5
        id: cache-downloads
        with:
          path: ${{ env.MODELDIR }}
          key: cache-downloads

      - name: Download models (if necessary)
        run: |
             mkdir -p $MODELDIR
             pushd $MODELDIR
             wget -q -nc https://zenodo.org/record/1169181/files/uxclumpy-cutoff.fits https://zenodo.org/record/1169181/files/uxclumpy-cutoff-omni.fits;
             popd

      - name: Cache conda
        uses: pat-s/always-upload-cache@v2.1.5
        id: cache-conda
        env:
          cache-name: cache-conda
          cache-version: 3
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.cache-version }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}-${{ env.cache-version }}
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get install -y ghostscript
          conda install -y -c https://cxc.cfa.harvard.edu/conda/ciao ciao sherpa ds9 ciao-contrib caldb_main 
          conda install -y ultranest coverage coveralls scipy "matplotlib>=3.3.0" h5py astropy requests cython tqdm coverage
          sudo sed -i '/PDF/s/none/read|write/' /etc/ImageMagick-6/policy.xml

      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Conda paths
        run: |
          pwd
          echo $PATH
          ls $CONDA/bin/
          which coverage

      - name: Conda download clean-up
        # we must keep below 5GB, otherwise caching fails
        # prefer keeping large files (ciao)
        run: |
            find ~/conda_pkgs_dir -type f -printf '%s\t%p\n' | sort -nr -k1,1 |
            { S=0; while read s l; do 
                ((S+=s)); [[ $S -gt 5000000000 ]] && rm -v "$l"; 
              done; }

      - name: Prepare testing
        run: |
          cp .coveragerc docker/testsrc
          cp .coveragerc examples/sherpa
          cp .coveragerc examples/xspec
          pushd docker/testsrc
          echo "backend: Agg" > matplotlibrc
          ls 
          rm *.nh

      - name: Test helper scripts
        run: |
          pushd docker/testsrc
          coverage run -p ../../fixkeywords.py combined_src.pi combined_bkg.pi combined_src.rmf combined_src.arf
          coverage run -p ../../gal.py combined_src.pi
          ls combined_src.pi.nh
          coverage run -p ../../autobackgroundmodel/fitbkg.py combined_bkg.pi combined_src.pi || exit 1
          coverage run -p ../../autobackgroundmodel/fitbkg.py combined_bkg.pi || exit 1
          coverage run -p ../../autobackgroundmodel/fitbkg.py || true
          coverage run -p ../../gal.py || true
          coverage run -p ../../fixkeywords.py || true
          git checkout .
          popd

      - name: Test examples
        run: |
            pushd examples/sherpa;
            # install interpolation code first
            echo $CONDA_PREFIX/lib/python* 
            ls /usr/include/numpy/ || true
            sudo ln -s $CONDA_PREFIX/lib/python${{ matrix.python-version }}/site-packages/numpy/core/include/numpy /usr/include/numpy
            ls /usr/include/numpy/;
            git clone https://github.com/JohannesBuchner/npyinterp.git;
            pushd npyinterp; make; popd;
            # run examples
            PYTHONPATH=../../:${PYTHONPATH}:npyinterp/ LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:npyinterp/ bash -v runall.sh || exit 1;
            popd;

      - name: Run XAGNFitter
        run: |
            pushd docker/testsrc;
            PYTHONPATH=../../:$PYTHONPATH WITHAPEC=0 coverage run -p ../../examples/sherpa/xagnfitter.py || exit 1;
            ls;
            popd;

      - name: Install
        run: |
          pip install . --user
          wc -l examples/sherpa/.cover* examples/xspec/.cover* docker/testsrc/.cover* .cover* || true

      - name: Coverage report
        run: |
          coverage combine examples/sherpa examples/xspec docker/testsrc .
          coverage report

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
